#include <emscripten/bind.h>
#include "aoo_source_js.hpp"



EMSCRIPTEN_BINDINGS(AooSource) {
	emscripten::class_<AooSourceJS>("AooSource")
		.constructor<AooId>()
		.function("setup", &AooSourceJS::setup)
		.function("reset", &AooSourceJS::reset)
		.function("setId", &AooSourceJS::setId)
		.function("removeAllSinks", &AooSourceJS::removeAllSinks)
		.function("setPacketSize", &AooSourceJS::setPacketSize)
		.function("setPingInterval", &AooSourceJS::setPingInterval)
		.function("setDllBandwidth", &AooSourceJS::setDllBandwidth)
		.function("setRedundancy", &AooSourceJS::setRedundancy)
		.function("setResendBufferSize", &AooSourceJS::setResendBufferSize)
		.function("setBinaryFormat", &AooSourceJS::setBinaryFormat)
		.function("setStreamTimeSendInterval", &AooSourceJS::setStreamTimeSendInterval)
		.function("setResampleMethod", &AooSourceJS::setResampleMethod)
		.function("setFormat", &AooSourceJS::setFormat)
		.function("addSink", &AooSourceJS::addSink)
		.function("removeSink", &AooSourceJS::removeSink)
		.function("handleInvite", &AooSourceJS::handleInvite)
		.function("handleUninvite", &AooSourceJS::handleUninvite)
		.function("activate", &AooSourceJS::activate)
		.function("setSinkChannelOffset", &AooSourceJS::setSinkChannelOffset)
		.function("startStream", &AooSourceJS::startStream)
		.function("stopStream", &AooSourceJS::stopStream)
		.function("setDynamicResampling", &AooSourceJS::setDynamicResampling)
		.function("setBufferSize", &AooSourceJS::setBufferSize)
		.function("getRealSampleRate", &AooSourceJS::getRealSampleRate)
		.function("eventsAvailable", &AooSourceJS::eventsAvailable)
		.function("process", &AooSourceJS::process)
		.function("handleMessage", &AooSourceJS::handleMessage)
		.function("send", &AooSourceJS::send)
		.function("setEventHandler", &AooSourceJS::setEventHandler)
		.function("pollEvents", &AooSourceJS::pollEvents)
		.function("addStreamMessage", &AooSourceJS::addStreamMessage)
		.function("setFormatOpus", &AooSourceJS::setFormatOpus)
		.function("setOpusBitrate", &AooSourceJS::setOpusBitrate)
		.function("setOpusComplexity", &AooSourceJS::setOpusComplexity)
		.function("setOpusSignalType", &AooSourceJS::setOpusSignalType)
		;
}